### PR TITLE
SS-7586 SS-7550 viewer major release update

### PR DESCRIPTION
**Pull request by snabela**
https://shapediver.atlassian.net/browse/SS-7586
https://shapediver.atlassian.net/browse/SS-7550

### CODE REVIEW

**Comment by snabela** [comment]
@MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?

**Comment by MajorMeerkatThe3rd** [comment]
> @MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?

@snabela I already found the issue. This seems to be specific to the major version and react. (I log the properties in the createViewport function now, but with react there is some circularity in the canvas element)

Something on the AppBuilder side: There is actually an error happening and thrown, but it is never displayed somewhere. Please check the code here: https://github.com/shapediver/AppBuilderSdk/blob/cb694ee37e940843ed8c26d1c4d8ecb11e11916f/src/store/useShapeDiverStoreViewer.ts#L54

**Comment by snabela** [comment]
> > @MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?
> 
> @snabela I already found the issue. This seems to be specific to the major version and react. (I log the properties in the createViewport function now, but with react there is some circularity in the canvas element)
> 
> Something on the AppBuilder side: There is actually an error happening and thrown, but it is never displayed somewhere. Please check the code here:
> 
> https://github.com/shapediver/AppBuilderSdk/blob/cb694ee37e940843ed8c26d1c4d8ecb11e11916f/src/store/useShapeDiverStoreViewer.ts#L54

Many thanks for the hint! I will improve this as part of this PR!

**Comment by snabela** [comment]
> > > @MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?
> > 
> > 
> > @snabela I already found the issue. This seems to be specific to the major version and react. (I log the properties in the createViewport function now, but with react there is some circularity in the canvas element)
> > Something on the AppBuilder side: There is actually an error happening and thrown, but it is never displayed somewhere. Please check the code here:
> > https://github.com/shapediver/AppBuilderSdk/blob/cb694ee37e940843ed8c26d1c4d8ecb11e11916f/src/store/useShapeDiverStoreViewer.ts#L54
> 
> Many thanks for the hint! I will improve this as part of this PR!

works now!

image

**Comment by MajorMeerkatThe3rd** [comment]
> > > > @MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?
> > > 
> > > 
> > > @snabela I already found the issue. This seems to be specific to the major version and react. (I log the properties in the createViewport function now, but with react there is some circularity in the canvas element)
> > > Something on the AppBuilder side: There is actually an error happening and thrown, but it is never displayed somewhere. Please check the code here:
> > > https://github.com/shapediver/AppBuilderSdk/blob/cb694ee37e940843ed8c26d1c4d8ecb11e11916f/src/store/useShapeDiverStoreViewer.ts#L54
> > 
> > 
> > Many thanks for the hint! I will improve this as part of this PR!
> 
> works now!
> 
> image

@snabela there was also another issues, should all be resolved now. please try it out

**Comment by snabela** [comment]
> > > > > @MajorMeerkatThe3rd please check out this branch, after updating to the major viewer release the viewport stays white. Did I miss something?
> > > > 
> > > > 
> > > > @snabela I already found the issue. This seems to be specific to the major version and react. (I log the properties in the createViewport function now, but with react there is some circularity in the canvas element)
> > > > Something on the AppBuilder side: There is actually an error happening and thrown, but it is never displayed somewhere. Please check the code here:
> > > > https://github.com/shapediver/AppBuilderSdk/blob/cb694ee37e940843ed8c26d1c4d8ecb11e11916f/src/store/useShapeDiverStoreViewer.ts#L54
> > > 
> > > 
> > > Many thanks for the hint! I will improve this as part of this PR!
> > 
> > 
> > works now!
> > image
> 
> @snabela there was also another issues, should all be resolved now. please try it out

@MajorMeerkatThe3rd works great now, many thanks! Please let me know once the viewer package is available publicly.

**Comment by snabela** [comment]
@MajorMeerkatThe3rd short question: do you see a better way to do this, and avoid the casting? https://github.com/shapediver/AppBuilderSdk/blob/53091bf1d0ff5e31d1c58a94df604b7c0b84a98b/src/store/useShapeDiverStoreParameters.ts#L99

**Pull request merged**
